### ISSUE TITLE
Discuss PR merge process

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/DeveloperGuides#14]
Something to consider for our PR process https://help.github.com/articles/about-pull-request-merges/

i believe this feature has been available for some time in Github, and i just hadn’t noticed it. We can choose to squash and merge commits into one when merging PRs.

@ucsdlib/developers - I’d be interested in your opinions on using this feature, pros/cons, etc.

**Comment by lsitu** [comment]
@mcritchlow This looks more like a convenient feature for us and I think it won't be bad to have it as an option.

**Comment by VivianChu** [comment]
@mcritchlow I think that feature squash and merge commits into one is good.

**Comment by mcritchlow** [comment]
closing in favor of the rebase strategy documented in 2f884613b
