### ISSUE TITLE
Code Review section in git.md is redundant

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/DeveloperGuides#8]
https://github.com/ucsdlib/DeveloperGuides/blob/master/protocol/git.md#review-code

Is redundant with code_review.md

**Comment by lsitu** [comment]
Yes, a little bit. Maybe we can change it for something related to close a PR?

**Comment by mcritchlow** [comment]
@lsitu I like that idea. Just keeping the context to something like:
- The last developer to sign off closes the PR
- The feature branch should be deleted after merging the PR
- .. ?

**Comment by lsitu** [comment]
It looks good. And maybe the develop can call for someone in the group to merge the PR and close it? I think this only works in some miscommunicated situations that the PR is ready for merging but the "last developer" is unclear.

**Comment by VivianChu** [comment]
@mcritchlow Are you going to delete that redundant section and only provide a link  to https://github.com/ucsdlib/DeveloperGuides/blob/master/protocol/code_review.md ?

**Comment by hweng** [comment]
@mcritchlow Agree to delete that redundant section.

**Comment by mcritchlow** [comment]
@VivianChu Honestly I'm just looking for excuses to create tickets to test out Zenhub :) That said, yes generally what you said is what I'm thinking. Potentially with the feedback from @lsitu as well

**Comment by mcritchlow** [comment]
@lsitu how about something like the following:
- If two or more developers have already signed off on a PR, the creator of the PR should ask for a merge

**Comment by lsitu** [comment]
Yep, it sounds like what we are doing now, which is flexible enough not to block it from progressing under that situation.

**Comment by mcritchlow** [comment]
@ucsdlib/developers please check out the linked PR. Feedback and change requests welcome.
